[build]
target = "index.html"

[watch]
ignore = [
    ".git",
    "target",
    "dist",
]

[[hooks]]
stage = "pre_build"
command = "tailwindcss"
command_arguments = ["-i", "input.css", "-o", "output.css", "--minify"]
